#!/usr/bin/env python3
"""
Environment Setup Helper
========================
Interactive script to help set up environment variables for the project.

Usage:
    python setup_env.py                      # Interactive setup
    python setup_env.py --frontend           # Setup frontend only
    python setup_env.py --backend            # Setup backend only
    python setup_env.py --env production     # Setup for production
"""

import os
import sys
import argparse
import secrets
import string
from pathlib import Path


class EnvSetupHelper:
    """Helper class for setting up environment files"""
    
    def __init__(self, environment='development'):
        self.environment = environment
        self.project_root = Path(__file__).parent
        self.frontend_env = self.project_root / '.env'
        self.backend_env = self.project_root / 'backend' / '.env'
    
    def run(self, frontend=True, backend=True):
        """Run the setup process"""
        print("\n" + "="*60)
        print(f"Environment Setup - {self.environment.upper()}")
        print("="*60 + "\n")
        
        if frontend:
            self.setup_frontend()
        
        if backend:
            self.setup_backend()
        
        print("\n" + "="*60)
        print("✅ Setup Complete!")
        print("="*60)
        print("\nNext steps:")
        print("1. Review the generated .env files")
        print("2. Update any placeholder values")
        print("3. Never commit .env files to git")
        print("4. Run 'python backend/validate_env.py' to verify\n")
    
    def setup_frontend(self):
        """Setup frontend .env file"""
        print("📦 Setting up Frontend Environment")
        print("-" * 60 + "\n")
        
        if self.frontend_env.exists():
            response = input(f".env already exists. Overwrite? (y/N): ").strip().lower()
            if response != 'y':
                print("⏭️  Skipping frontend setup\n")
                return
        
        # Read .env.example
        example_file = self.project_root / '.env.example'
        if not example_file.exists():
            print("❌ .env.example not found!")
            return
        
        # Get values
        if self.environment == 'development':
            api_url = 'http://localhost:8000/api'
            app_url = 'http://localhost:5173'
        else:
            api_url = input("Backend API URL (e.g., https://api.yourapp.com/api): ").strip()
            app_url = input("Frontend URL (e.g., https://yourapp.com): ").strip()
        
        # Create .env content
        env_content = f"""# Frontend Environment Variables - {self.environment}
# Generated by setup_env.py

# ==============================================
# API Configuration
# ==============================================
VITE_API_URL={api_url}
VITE_APP_URL={app_url}
VITE_APP_NAME=Cohort Management System

# ==============================================
# Feature Flags
# ==============================================
VITE_ENABLE_GAMIFICATION=true
VITE_ENABLE_CHAT=true
VITE_ENABLE_NOTIFICATIONS=true
VITE_ENABLE_ANALYTICS=false

# ==============================================
# Configuration
# ==============================================
VITE_MAX_FILE_SIZE_MB=10
VITE_API_TIMEOUT_MS=30000
VITE_DEFAULT_PAGE_SIZE=20

# ==============================================
# Debug (Development Only)
# ==============================================
VITE_DEBUG_LOGGING={'true' if self.environment == 'development' else 'false'}
VITE_ENV={self.environment}
"""
        
        # Write file
        with open(self.frontend_env, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Created {self.frontend_env}")
        print(f"   API URL: {api_url}")
        print(f"   App URL: {app_url}\n")
    
    def setup_backend(self):
        """Setup backend .env file"""
        print("🔧 Setting up Backend Environment")
        print("-" * 60 + "\n")
        
        if self.backend_env.exists():
            response = input(f"backend/.env already exists. Overwrite? (y/N): ").strip().lower()
            if response != 'y':
                print("⏭️  Skipping backend setup\n")
                return
        
        # Generate secrets
        secret_key = self.generate_secret_key()
        jwt_secret = self.generate_secret_key(32)
        
        # Get values
        if self.environment == 'development':
            debug = 'True'
            database_url = ''  # Will use SQLite
            allowed_hosts = 'localhost,127.0.0.1'
            cors_origins = 'http://localhost:5173,http://localhost:5174'
        else:
            debug = 'False'
            database_url = input("Database URL (leave empty to skip): ").strip()
            allowed_hosts = input("Allowed hosts (comma-separated): ").strip()
            cors_origins = input("CORS allowed origins (comma-separated): ").strip()
        
        # Create .env content
        env_content = f"""# Backend Environment Variables - {self.environment}
# Generated by setup_env.py

# ==============================================
# Django Core Settings
# ==============================================
SECRET_KEY={secret_key}
DEBUG={debug}
DJANGO_ENV={self.environment}
ALLOWED_HOSTS={allowed_hosts}

# ==============================================
# Database Configuration
# ==============================================
DATABASE_URL={database_url}

# ==============================================
# CORS Settings
# ==============================================
CORS_ALLOWED_ORIGINS={cors_origins}
CORS_ALLOW_ALL_ORIGINS=False

# ==============================================
# JWT Authentication Settings
# ==============================================
JWT_ACCESS_TOKEN_LIFETIME_MINUTES=60
JWT_REFRESH_TOKEN_LIFETIME_DAYS=7
JWT_ALGORITHM=HS256
JWT_SECRET_KEY={jwt_secret}

# ==============================================
# Static & Media Files
# ==============================================
STATIC_URL=/static/
STATIC_ROOT=staticfiles
MEDIA_URL=/media/
MEDIA_ROOT=media
"""
        
        # Add test passwords only for development
        if self.environment == 'development':
            env_content += """
# ==============================================
# Test User Passwords (Development ONLY)
# ==============================================
TEST_ADMIN_PASSWORD=admin123
TEST_MENTOR_PASSWORD=mentor123
TEST_STUDENT_PASSWORD=pass123#
TEST_FLOORWING_PASSWORD=floorwing123
TEST_USER_PASSWORD=testpass123
TEST_DEFAULT_PASSWORD=test123
"""
        
        # Write file
        with open(self.backend_env, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Created {self.backend_env}")
        print(f"   SECRET_KEY: {secret_key[:20]}... (generated)")
        print(f"   JWT_SECRET_KEY: {jwt_secret[:20]}... (generated)")
        print(f"   DEBUG: {debug}")
        if database_url:
            print(f"   DATABASE_URL: {database_url[:30]}...")
        else:
            print(f"   DATABASE_URL: (empty - will use SQLite)")
        print()
    
    @staticmethod
    def generate_secret_key(length=50):
        """Generate a random secret key"""
        alphabet = string.ascii_letters + string.digits + '!@#$%^&*(-_=+)'
        return ''.join(secrets.choice(alphabet) for _ in range(length))


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description='Interactive environment setup helper'
    )
    parser.add_argument(
        '--env',
        choices=['development', 'staging', 'production'],
        default='development',
        help='Environment to setup (default: development)'
    )
    parser.add_argument(
        '--frontend',
        action='store_true',
        help='Setup frontend only'
    )
    parser.add_argument(
        '--backend',
        action='store_true',
        help='Setup backend only'
    )
    
    args = parser.parse_args()
    
    # If neither specified, do both
    if not args.frontend and not args.backend:
        frontend = True
        backend = True
    else:
        frontend = args.frontend
        backend = args.backend
    
    # Create helper and run
    helper = EnvSetupHelper(environment=args.env)
    helper.run(frontend=frontend, backend=backend)


if __name__ == '__main__':
    main()
