# Generated by Django 4.2.7 on 2026-02-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.CharField(db_index=True, help_text='UUID from Supabase auth.users table', max_length=255, unique=True)),
                ('supabase_email', models.EmailField(db_index=True, help_text='Email from Supabase auth', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Can this user authenticate?')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supabase_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supabase User Mapping',
                'verbose_name_plural': 'Supabase User Mappings',
                'db_table': 'supabase_user_mapping',
                'indexes': [models.Index(fields=['supabase_id'], name='supabase_us_supabas_bd9982_idx'), models.Index(fields=['supabase_email'], name='supabase_us_supabas_d5e580_idx')],
            },
        ),
    ]
